### ISSUE TITLE
ERROR: Module "Auto-Pet-master" could not be loaded!

### ISSUE THREAD

**Issue by pepsimemen** [PsykoDev/Auto-Pet#1]
[mods] ERROR: Module "Auto-Pet-master" could not be loaded!
[mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
 Error: Cannot find module 'TeraToolbox\mods\Auto-Pet-master'
Require stack:
- TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js
- TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js
- TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js
- TeraToolbox\node_modules\tera-network-proxy\lib\index.js
- TeraToolbox\bin\connectionManager.js
- TeraToolbox\bin\proxy.js
- TeraToolbox\bin\loader-gui.js
- TeraToolbox\bin\index-gui.js
- TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (TeraToolbox\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at ModuleManager.load (TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:148:43)
    at TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (TeraToolbox\bin\connectionManager.js:55:47) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\moduleManager.js',
    'TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\index.js',
    'TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\index.js',
    'TeraToolbox\\node_modules\\tera-network-proxy\\lib\\index.js',
    'TeraToolbox\\bin\\connectionManager.js',
    'TeraToolbox\\bin\\proxy.js',
    'TeraToolbox\\bin\\loader-gui.js',
    'TeraToolbox\\bin\\index-gui.js',
    'TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
    undefined
  ]
}

That happend :B

**Comment by PsykoDev** [comment]
AH wth

**Comment by pepsimemen** [comment]
suddenly it works, did nothing, gud mod 10/10
